//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_task
    {
        public int task_id { get; set; }
        public string task_name { get; set; }
        public string task_description { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public string status { get; set; }
        public Nullable<int> priority { get; set; }
    }
}
